# Generated by Django 5.0.6 on 2024-09-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
