# Generated by Django 5.1 on 2024-09-02 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_description_assignment_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Note',
        ),
    ]
