# Generated by Django 5.1 on 2024-09-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_assignment_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
