# Generated by Django 5.1 on 2024-09-03 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 11, 28, 56, 469116)),
        ),
    ]
