# Generated by Django 5.1 on 2024-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_assignment_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_name',
            field=models.CharField(max_length=11),
        ),
    ]
